/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/albums/{artist}/{album}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** An album of an artist */
        readonly get: operations["getAlbum"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/albums/{artist}/{album}/cover": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Set the cover of every song in an album */
        readonly put: operations["setAlbumCover"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/artists/{artist}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** An artist's albums and features */
        readonly get: operations["getArtist"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/downloads": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Download status */
        readonly get: operations["getDownloads"];
        readonly put?: never;
        /**
         * Queue a download
         * @description Accepts a link to any site yt-dlp supports, or a search term that is looked up on YouTube Music.
         */
        readonly post: operations["enqueueDownload"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/downloads/current": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /** Abort the running download */
        readonly delete: operations["abortDownload"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Live updates
         * @description Server-sent events for library and download changes. The stream ends if the client falls too far behind; reconnect and refetch.
         */
        readonly get: operations["events"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/home": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Newest songs */
        readonly get: operations["getHome"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/listings/{kind}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Songs grouped by a criterion */
        readonly get: operations["getListing"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/search": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Search songs by title, artist, album and year */
        readonly get: operations["search"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/songs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * All songs
         * @description Every song in the collection, sorted by title. Other endpoints refer to songs by ID only.
         */
        readonly get: operations["listSongs"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/songs/random": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** A random song */
        readonly get: operations["getRandomSong"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/songs/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Song details */
        readonly get: operations["getSong"];
        /**
         * Edit a song
         * @description Replaces all editable fields of a song.
         */
        readonly put: operations["updateSong"];
        readonly post?: never;
        /** Delete a song and its files */
        readonly delete: operations["deleteSong"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/songs/{id}/cover": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Replace a song's cover
         * @description The image is cropped to a square.
         */
        readonly put: operations["setSongCover"];
        readonly post?: never;
        /** Remove a song's cover */
        readonly delete: operations["deleteSongCover"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly Album: {
            readonly artist: string;
            readonly songIds: readonly string[];
            readonly title: string;
        };
        readonly Artist: {
            readonly albums: readonly components["schemas"]["Album"][];
            /** @description IDs of songs by other artists featuring this one */
            readonly featured: readonly string[];
            readonly name: string;
            /**
             * Format: double
             * @description Total length of all songs in seconds
             */
            readonly playTime: number;
            /** Format: int64 */
            readonly yearEnd?: number;
            /** Format: int64 */
            readonly yearStart?: number;
        };
        readonly AudioFile: {
            readonly name: string;
            /** Format: int64 */
            readonly size: number;
        };
        readonly Cover: {
            /** @description Dominant color as #rrggbb */
            readonly color?: string;
            /**
             * Format: int64
             * @description Width and height in pixels; covers are square
             */
            readonly size: number;
        };
        readonly DownloadFailure: {
            readonly message: string;
            /** @description Downloader output, for diagnosis */
            readonly output?: string;
            /** @enum {string} */
            readonly reason: "aborted" | "tool_failed" | "no_audio" | "invalid_audio" | "duplicate" | "internal";
            /** @description The existing song when the reason is duplicate */
            readonly songId?: string;
        };
        readonly DownloadFinishedEvent: {
            readonly error?: components["schemas"]["DownloadFailure"];
        };
        readonly DownloadStartedEvent: Record<string, never>;
        readonly DownloadStatus: {
            readonly lastError?: components["schemas"]["DownloadFailure"];
            /**
             * Format: int64
             * @description Downloads waiting after the current one
             */
            readonly queued: number;
            readonly running: boolean;
            /** @description What the downloader is fetching right now */
            readonly url?: string;
        };
        readonly EnqueueDownloadRequest: {
            /** @description URL or search term */
            readonly query: string;
        };
        readonly ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            readonly location?: string;
            /** @description Error message text */
            readonly message?: string;
            /** @description The value at the given location */
            readonly value?: unknown;
        };
        readonly Group: {
            readonly description?: string;
            readonly link?: string;
            readonly songIds: readonly string[];
            readonly title: string;
        };
        readonly Home: {
            readonly songIds: readonly string[];
            /** @description Whether all songs were added today */
            readonly today: boolean;
        };
        readonly Playback: {
            /**
             * Format: double
             * @description Seconds into the audio file where the song ends
             */
            readonly end: number;
            /**
             * Format: double
             * @description Seconds into the audio file where the song starts
             */
            readonly start: number;
        };
        readonly Problem: {
            /**
             * @description Machine-readable error code
             * @enum {string}
             */
            readonly code: "bad_request" | "validation" | "not_found" | "already_downloaded" | "queue_full" | "not_downloading" | "internal" | "other";
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            readonly detail?: string;
            /** @description Optional list of individual error details */
            readonly errors?: readonly components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            readonly instance?: string;
            /** @description Kind of resource that was not found (song, album, artist) */
            readonly resource?: string;
            /** @description The existing song when the error is already_downloaded */
            readonly songId?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            readonly status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            readonly title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            readonly type: string;
        };
        readonly SearchResult: {
            /** @description Best match first */
            readonly songIds: readonly string[];
        };
        readonly SongAddedEvent: {
            readonly song: components["schemas"]["SongSummary"];
        };
        readonly SongDeletedEvent: {
            readonly id: string;
        };
        readonly SongDetail: {
            /** Format: date-time */
            readonly added: string;
            readonly album?: string;
            readonly artist?: string;
            readonly cover?: components["schemas"]["Cover"];
            /**
             * Format: double
             * @description Length of the audio file in seconds
             */
            readonly duration: number;
            readonly file: components["schemas"]["AudioFile"];
            readonly id: string;
            readonly imported: boolean;
            /** Format: date-time */
            readonly lastEdit: string;
            readonly playback: components["schemas"]["Playback"];
            /** @description IDs of similar songs */
            readonly related: readonly string[];
            readonly sourceUrl: string;
            readonly sync: boolean;
            readonly title: string;
            /** Format: int64 */
            readonly year?: number;
        };
        readonly SongEditBody: {
            readonly album: string;
            readonly artist: string;
            /** Format: double */
            readonly end: number;
            /** Format: double */
            readonly start: number;
            readonly sync: boolean;
            readonly title: string;
            /**
             * Format: int64
             * @description Omit to clear the year
             */
            readonly year?: number;
        };
        readonly SongSummary: {
            /** Format: date-time */
            readonly added: string;
            readonly album?: string;
            readonly artist?: string;
            readonly cover?: components["schemas"]["Cover"];
            /**
             * Format: double
             * @description Length of the audio file in seconds
             */
            readonly duration: number;
            readonly id: string;
            /** Format: date-time */
            readonly lastEdit: string;
            readonly playback: components["schemas"]["Playback"];
            readonly sync: boolean;
            readonly title: string;
            /** Format: int64 */
            readonly year?: number;
        };
        readonly SongUpdatedEvent: {
            readonly song: components["schemas"]["SongSummary"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Album = components['schemas']['Album'];
export type Artist = components['schemas']['Artist'];
export type AudioFile = components['schemas']['AudioFile'];
export type Cover = components['schemas']['Cover'];
export type DownloadFailure = components['schemas']['DownloadFailure'];
export type DownloadFinishedEvent = components['schemas']['DownloadFinishedEvent'];
export type DownloadStartedEvent = components['schemas']['DownloadStartedEvent'];
export type DownloadStatus = components['schemas']['DownloadStatus'];
export type EnqueueDownloadRequest = components['schemas']['EnqueueDownloadRequest'];
export type ErrorDetail = components['schemas']['ErrorDetail'];
export type Group = components['schemas']['Group'];
export type Home = components['schemas']['Home'];
export type Playback = components['schemas']['Playback'];
export type Problem = components['schemas']['Problem'];
export type SearchResult = components['schemas']['SearchResult'];
export type SongAddedEvent = components['schemas']['SongAddedEvent'];
export type SongDeletedEvent = components['schemas']['SongDeletedEvent'];
export type SongDetail = components['schemas']['SongDetail'];
export type SongEditBody = components['schemas']['SongEditBody'];
export type SongSummary = components['schemas']['SongSummary'];
export type SongUpdatedEvent = components['schemas']['SongUpdatedEvent'];
export type $defs = Record<string, never>;
export interface operations {
    readonly getAlbum: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly artist: string;
                readonly album: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Album"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly setAlbumCover: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly artist: string;
                readonly album: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "multipart/form-data": {
                    /** Format: binary */
                    readonly cover: string;
                };
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getArtist: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly artist: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Artist"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getDownloads: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DownloadStatus"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly enqueueDownload: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["EnqueueDownloadRequest"];
            };
        };
        readonly responses: {
            /** @description Accepted */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DownloadStatus"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly abortDownload: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly events: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "text/event-stream": readonly ({
                        readonly data: components["schemas"]["DownloadFinishedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        readonly event: "downloadFinished";
                        /** @description The event ID. */
                        readonly id?: number;
                        /** @description The retry time in milliseconds. */
                        readonly retry?: number;
                    } | {
                        readonly data: components["schemas"]["DownloadStartedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        readonly event: "downloadStarted";
                        /** @description The event ID. */
                        readonly id?: number;
                        /** @description The retry time in milliseconds. */
                        readonly retry?: number;
                    } | {
                        readonly data: components["schemas"]["SongAddedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        readonly event: "songAdded";
                        /** @description The event ID. */
                        readonly id?: number;
                        /** @description The retry time in milliseconds. */
                        readonly retry?: number;
                    } | {
                        readonly data: components["schemas"]["SongDeletedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        readonly event: "songDeleted";
                        /** @description The event ID. */
                        readonly id?: number;
                        /** @description The retry time in milliseconds. */
                        readonly retry?: number;
                    } | {
                        readonly data: components["schemas"]["SongUpdatedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        readonly event: "songUpdated";
                        /** @description The event ID. */
                        readonly id?: number;
                        /** @description The retry time in milliseconds. */
                        readonly retry?: number;
                    })[];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getHome: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Home"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getListing: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly kind: "title" | "artist" | "year" | "incomplete" | "unsynced" | "edited" | "added";
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Group"][];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly search: {
        readonly parameters: {
            readonly query: {
                readonly q: string;
                /** @description 0 means no limit */
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly listSongs: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SongSummary"][];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getRandomSong: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SongSummary"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getSong: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Song ID */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SongDetail"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly updateSong: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Song ID */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SongEditBody"];
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SongSummary"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly deleteSong: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Song ID */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly setSongCover: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Song ID */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "multipart/form-data": {
                    /** Format: binary */
                    readonly cover: string;
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SongSummary"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly deleteSongCover: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Song ID */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SongSummary"];
                };
            };
            /** @description Error */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const pathsApiV1ListingsKindGetParametersPathKindValues: ReadonlyArray<FlattenedDeepRequired<paths>["/api/v1/listings/{kind}"]["get"]["parameters"]["path"]["kind"]> = ["title", "artist", "year", "incomplete", "unsynced", "edited", "added"];
export const downloadFailureReasonValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["DownloadFailure"]["reason"]> = ["aborted", "tool_failed", "no_audio", "invalid_audio", "duplicate", "internal"];
export const problemCodeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Problem"]["code"]> = ["bad_request", "validation", "not_found", "already_downloaded", "queue_full", "not_downloading", "internal", "other"];
