/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/albums/{artist}/{album}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An album of an artist */
        get: operations["getAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{artist}/{album}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the cover of every song in an album */
        put: operations["setAlbumCover"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress of the background audio analysis */
        get: operations["getAnalysisStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artists/{artist}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An artist's albums and features */
        get: operations["getArtist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download status */
        get: operations["getDownloads"];
        put?: never;
        /**
         * Queue a download
         * @description Accepts a link to any site yt-dlp supports, or a search term that is looked up on YouTube Music.
         */
        post: operations["enqueueDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/downloads/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Abort the running download */
        delete: operations["abortDownload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live updates
         * @description Server-sent events for library and download changes. The stream ends if the client falls too far behind; reconnect and refetch.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Newest songs */
        get: operations["getHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Songs grouped by a criterion */
        get: operations["getListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Songs to play next
         * @description Picks synced songs to continue playback after the queue runs out. Results are random; call again for more.
         */
        get: operations["nextSongs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search songs by title, artist, album and year */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All songs
         * @description Every song in the collection, sorted by title. Other endpoints refer to songs by ID only.
         */
        get: operations["listSongs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A random song */
        get: operations["getRandomSong"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Song details */
        get: operations["getSong"];
        /**
         * Edit a song
         * @description Replaces all editable fields of a song.
         */
        put: operations["updateSong"];
        post?: never;
        /** Delete a song and its files */
        delete: operations["deleteSong"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a song's cover
         * @description The image is cropped to a square.
         */
        put: operations["setSongCover"];
        post?: never;
        /** Remove a song's cover */
        delete: operations["deleteSongCover"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Album: {
            artist: string;
            songIds: string[];
            title: string;
        };
        Analysis: {
            /** Format: date-time */
            analyzedAt?: string;
            /** Format: double */
            beatStrength?: number;
            /** Format: double */
            bpm?: number;
            /** @description Camelot wheel code, e.g. 8A */
            camelot?: string;
            /**
             * Format: double
             * @description Spectral centroid (brightness) in Hz
             */
            centroid?: number;
            /** Format: double */
            energyDb?: number;
            error?: string;
            /**
             * Format: double
             * @description Spectral flatness, 0 tonal … 1 noisy
             */
            flatness?: number;
            /** @description e.g. A minor */
            key?: string;
            /** Format: double */
            keyStrength?: number;
            /** Format: double */
            loudnessLufs?: number;
            /** Format: double */
            loudnessRange?: number;
            /**
             * Format: double
             * @description Note onsets per second
             */
            onsetRate?: number;
            /** @enum {string} */
            status: "pending" | "done" | "failed";
        };
        AnalysisStatus: {
            /** Format: int64 */
            done: number;
            running: boolean;
            /** Format: int64 */
            total: number;
        };
        Artist: {
            albums: components["schemas"]["Album"][];
            /** @description IDs of songs by other artists featuring this one */
            featured: string[];
            name: string;
            /**
             * Format: double
             * @description Total length of all songs in seconds
             */
            playTime: number;
            /** Format: int64 */
            yearEnd?: number;
            /** Format: int64 */
            yearStart?: number;
        };
        AudioFile: {
            name: string;
            /** Format: int64 */
            size: number;
        };
        Cover: {
            /** @description Dominant color as #rrggbb */
            color?: string;
            /**
             * Format: int64
             * @description Width and height in pixels; covers are square
             */
            size: number;
        };
        DownloadFailure: {
            message: string;
            /** @description Downloader output, for diagnosis */
            output?: string;
            /** @enum {string} */
            reason: "aborted" | "tool_failed" | "no_audio" | "invalid_audio" | "duplicate" | "internal";
            /** @description The existing song when the reason is duplicate */
            songId?: string;
        };
        DownloadFinishedEvent: {
            error?: components["schemas"]["DownloadFailure"];
        };
        DownloadStartedEvent: Record<string, never>;
        DownloadStatus: {
            lastError?: components["schemas"]["DownloadFailure"];
            /**
             * Format: int64
             * @description Downloads waiting after the current one
             */
            queued: number;
            running: boolean;
            /** @description What the downloader is fetching right now */
            url?: string;
        };
        EnqueueDownloadRequest: {
            /** @description URL or search term */
            query: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        Group: {
            description?: string;
            link?: string;
            songIds: string[];
            title: string;
        };
        Home: {
            songIds: string[];
            /** @description Whether all songs were added today */
            today: boolean;
        };
        NextSong: {
            /** @description Why the song was picked; 1 is neutral. For debugging only. */
            factors: {
                [key: string]: number;
            };
            id: string;
            /** Format: double */
            score: number;
        };
        NextSongs: {
            songs: components["schemas"]["NextSong"][];
        };
        Playback: {
            /**
             * Format: double
             * @description Seconds into the audio file where the song ends
             */
            end: number;
            /**
             * Format: double
             * @description Seconds into the audio file where the song starts
             */
            start: number;
        };
        Problem: {
            /**
             * @description Machine-readable error code
             * @enum {string}
             */
            code: "bad_request" | "validation" | "not_found" | "already_downloaded" | "queue_full" | "not_downloading" | "internal" | "other";
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /** @description Kind of resource that was not found (song, album, artist) */
            resource?: string;
            /** @description The existing song when the error is already_downloaded */
            songId?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        SearchResult: {
            /** @description Best match first */
            songIds: string[];
        };
        SongAddedEvent: {
            song: components["schemas"]["SongSummary"];
        };
        SongDeletedEvent: {
            id: string;
        };
        SongDetail: {
            /** Format: date-time */
            added: string;
            album?: string;
            analysis: components["schemas"]["Analysis"];
            artist?: string;
            cover?: components["schemas"]["Cover"];
            /**
             * Format: double
             * @description Length of the audio file in seconds
             */
            duration: number;
            file: components["schemas"]["AudioFile"];
            id: string;
            imported: boolean;
            /** Format: date-time */
            lastEdit: string;
            /**
             * Format: double
             * @description Integrated loudness in LUFS, once the song is analysed; used to play songs equally loud
             */
            loudness?: number;
            playback: components["schemas"]["Playback"];
            /** @description IDs of similar songs */
            related: string[];
            sourceUrl: string;
            sync: boolean;
            title: string;
            /** Format: int64 */
            year?: number;
        };
        SongEditBody: {
            album: string;
            artist: string;
            /** Format: double */
            end: number;
            /** Format: double */
            start: number;
            sync: boolean;
            title: string;
            /**
             * Format: int64
             * @description Omit to clear the year
             */
            year?: number;
        };
        SongSummary: {
            /** Format: date-time */
            added: string;
            album?: string;
            artist?: string;
            cover?: components["schemas"]["Cover"];
            /**
             * Format: double
             * @description Length of the audio file in seconds
             */
            duration: number;
            id: string;
            /** Format: date-time */
            lastEdit: string;
            /**
             * Format: double
             * @description Integrated loudness in LUFS, once the song is analysed; used to play songs equally loud
             */
            loudness?: number;
            playback: components["schemas"]["Playback"];
            sync: boolean;
            title: string;
            /** Format: int64 */
            year?: number;
        };
        SongUpdatedEvent: {
            song: components["schemas"]["SongSummary"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Album = components['schemas']['Album'];
export type Analysis = components['schemas']['Analysis'];
export type AnalysisStatus = components['schemas']['AnalysisStatus'];
export type Artist = components['schemas']['Artist'];
export type AudioFile = components['schemas']['AudioFile'];
export type Cover = components['schemas']['Cover'];
export type DownloadFailure = components['schemas']['DownloadFailure'];
export type DownloadFinishedEvent = components['schemas']['DownloadFinishedEvent'];
export type DownloadStartedEvent = components['schemas']['DownloadStartedEvent'];
export type DownloadStatus = components['schemas']['DownloadStatus'];
export type EnqueueDownloadRequest = components['schemas']['EnqueueDownloadRequest'];
export type ErrorDetail = components['schemas']['ErrorDetail'];
export type Group = components['schemas']['Group'];
export type Home = components['schemas']['Home'];
export type NextSong = components['schemas']['NextSong'];
export type NextSongs = components['schemas']['NextSongs'];
export type Playback = components['schemas']['Playback'];
export type Problem = components['schemas']['Problem'];
export type SearchResult = components['schemas']['SearchResult'];
export type SongAddedEvent = components['schemas']['SongAddedEvent'];
export type SongDeletedEvent = components['schemas']['SongDeletedEvent'];
export type SongDetail = components['schemas']['SongDetail'];
export type SongEditBody = components['schemas']['SongEditBody'];
export type SongSummary = components['schemas']['SongSummary'];
export type SongUpdatedEvent = components['schemas']['SongUpdatedEvent'];
export type $defs = Record<string, never>;
export interface operations {
    getAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist: string;
                album: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Album"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setAlbumCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist: string;
                album: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    cover: string;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAnalysisStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artist"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDownloads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    enqueueDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnqueueDownloadRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    abortDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": ({
                        data: components["schemas"]["AnalysisStatus"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "analysisProgress";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["DownloadFinishedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "downloadFinished";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["DownloadStartedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "downloadStarted";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["SongAddedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "songAdded";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["SongDeletedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "songDeleted";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["SongUpdatedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "songUpdated";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    })[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "title" | "artist" | "year" | "incomplete" | "unsynced" | "edited" | "added";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    nextSongs: {
        parameters: {
            query?: {
                /** @description The song playing now, if any */
                current?: string;
                count?: number;
                /** @description Recently played songs to avoid */
                exclude?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextSongs"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                /** @description 0 means no limit */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listSongs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongSummary"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRandomSong: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Song ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Song ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SongEditBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Song ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setSongCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Song ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    cover: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSongCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Song ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongSummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const pathsApiV1ListingsKindGetParametersPathKindValues: ReadonlyArray<FlattenedDeepRequired<paths>["/api/v1/listings/{kind}"]["get"]["parameters"]["path"]["kind"]> = ["title", "artist", "year", "incomplete", "unsynced", "edited", "added"];
export const analysisStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Analysis"]["status"]> = ["pending", "done", "failed"];
export const downloadFailureReasonValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["DownloadFailure"]["reason"]> = ["aborted", "tool_failed", "no_audio", "invalid_audio", "duplicate", "internal"];
export const problemCodeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Problem"]["code"]> = ["bad_request", "validation", "not_found", "already_downloaded", "queue_full", "not_downloading", "internal", "other"];
