name: Build project

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Download tags which the git command needs later
      run: git fetch --prune --unshallow

    - name: Runnning build/generation script
      shell: bash
      run: |
        bash ./release.sh
        
    - name: Generate tag name
      run: echo "TAG_NAME=$(git rev-parse --short HEAD)" >> $GITHUB_ENV  
      
    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: releases/*.zip
        tag_name: ${{ env.TAG_NAME }}
        fail_on_unmatched_files: true
        body_path: release.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
